export const seedData = [
    // Repertoire
    { title: "Fat Lip", artist: "Sum 41", tags: ["Repertoire"] },
    { title: "I Will Survive", artist: "Gloria Gaynor", tags: ["Repertoire"] },
    { title: "Runaway Baby", artist: "Bruno Mars", tags: ["Repertoire"] },
    { title: "Since U Been Gone", artist: "Kelly Clarkson", tags: ["Repertoire"] },
    { title: "Only One", artist: "Yellowcard", tags: ["Repertoire"] },
    { title: "Welcome to the Black Parade", artist: "My Chemical Romance", tags: ["Repertoire"] },
    { title: "Sweet Caroline", artist: "Neil Diamond", tags: ["Repertoire"] },
    { title: "Careless Whisper", artist: "George Michael", tags: ["Repertoire"] },
    { title: "Perfect", artist: "Simple Plan", tags: ["Repertoire"] },
    { title: "Dust in the Wind", artist: "Kansas", tags: ["Repertoire"] },
    { title: "No Diggity", artist: "Blackstreet", tags: ["Repertoire"] },
    { title: "Pony", artist: "Ginuwine", tags: ["Repertoire"] },
    { title: "Crazy", artist: "Gnarls Barkley", tags: ["Repertoire"] },
    { title: "Fuck You", artist: "CeeLo Green", tags: ["Repertoire"] },
    { title: "Superstition", artist: "Stevie Wonder", tags: ["Repertoire"] },
    { title: "First Date", artist: "Blink-182", tags: ["Repertoire"] },
    { title: "I Miss You", artist: "Blink-182", tags: ["Repertoire"] },
    { title: "Undone - The Sweater Song", artist: "Weezer", tags: ["Repertoire"] },
    { title: "Lost At Sea", artist: "Zedd", tags: ["Repertoire"] },
    { title: "TiK ToK", artist: "Kesha", tags: ["Repertoire"] },
    { title: "Call Me Maybe", artist: "Carly Rae Jepsen", tags: ["Repertoire"] },
    { title: "Dance, Dance", artist: "Fall Out Boy", tags: ["Repertoire"] },
    { title: "Talk Dirty", artist: "Jason Derulo", tags: ["Repertoire"] },
    { title: "My Heart Will Go On", artist: "Celine Dion", tags: ["Repertoire"] },
    { title: "Hello", artist: "Lionel Richie", tags: ["Repertoire"] },
    { title: "Date Rape", artist: "Sublime", tags: ["Repertoire"] },
    { title: "Love Story", artist: "Taylor Swift", tags: ["Repertoire"] },
    { title: "Gold Digger", artist: "Kanye West", tags: ["Repertoire"] },
    { title: "American Boy", artist: "Estelle ft. Kanye West", tags: ["Repertoire"] },
    { title: "Flashdance... What a Feeling", artist: "Irene Cara", tags: ["Repertoire"] },
    { title: "Holding Out for a Hero", artist: "Bonnie Tyler", tags: ["Repertoire"] },
    { title: "Just Friends", artist: "Biz Markie", tags: ["Repertoire"] },
    { title: "Total Eclipse of the Heart", artist: "Bonnie Tyler", tags: ["Repertoire"] },
    { title: "This Love", artist: "Maroon 5", tags: ["Repertoire"] },
    { title: "We Are Young", artist: "Fun.", tags: ["Repertoire"] },
    { title: "Gangsta's Paradise", artist: "Coolio", tags: ["Repertoire"] },
    { title: "Parasite", artist: "Eve 6", tags: ["Repertoire"] },
    { title: "Stay the Night", artist: "Zedd ft. Hayley Williams", tags: ["Repertoire"] },
    { title: "La La La", artist: "Naughty Boy ft. Sam Smith", tags: ["Repertoire"] },
    { title: "Forgot About Dre", artist: "Dr. Dre ft. Eminem", tags: ["Repertoire"] },
    { title: "Wannabe", artist: "Spice Girls", tags: ["Repertoire"] },
    { title: "Blister in the Sun", artist: "Violent Femmes", tags: ["Repertoire"] },
    { title: "Bitch Better Have My Money", artist: "Rihanna", tags: ["Repertoire"] },
    { title: "Drunk in Love", artist: "Beyoncé", tags: ["Repertoire"] },
    { title: "Always", artist: "Atlantic Starr", tags: ["Repertoire"] },
    { title: "Bang Bang", artist: "Jessie J, Ariana Grande, Nicki Minaj", tags: ["Repertoire"] },
    { title: "Formation", artist: "Beyoncé", tags: ["Repertoire"] },
    { title: "Let It Go", artist: "Idina Menzel", tags: ["Repertoire"] },
    { title: "Umbrella", artist: "Rihanna", tags: ["Repertoire"] },
    { title: "Why Don't You Get A Job?", artist: "The Offspring", tags: ["Repertoire"] },
    { title: "Pretty Fly (For A White Guy)", artist: "The Offspring", tags: ["Repertoire"] },
    { title: "All My Life", artist: "K-Ci & JoJo", tags: ["Repertoire"] },
    { title: "I'm On A Boat", artist: "The Lonely Island", tags: ["Repertoire"] },
    { title: "Paris (Ooh La La)", artist: "Grace Potter & The Nocturnals", tags: ["Repertoire"] },
    { title: "Buddy Holly", artist: "Weezer", tags: ["Repertoire"] },
    { title: "Hard to Say I'm Sorry", artist: "Chicago", tags: ["Repertoire"] },
    { title: "Are You That Somebody?", artist: "Aaliyah", tags: ["Repertoire"] },
    { title: "Say My Name", artist: "Destiny's Child", tags: ["Repertoire"] },
    { title: "River", artist: "Bishop Briggs", tags: ["Repertoire"] },
    { title: "Stacy's Mom", artist: "Fountains of Wayne", tags: ["Repertoire"] },
    { title: "Livin' on a Prayer", artist: "Bon Jovi", tags: ["Repertoire"] },
    { title: "Here", artist: "Alessia Cara", tags: ["Repertoire"] },
    { title: "Fight For Your Right", artist: "Beastie Boys", tags: ["Repertoire"] },
    { title: "Talking Body", artist: "Tove Lo", tags: ["Repertoire"] },
    { title: "I Write Sins Not Tragedies", artist: "Panic! At The Disco", tags: ["Repertoire"] },
    { title: "Hey There Delilah", artist: "Plain White T's", tags: ["Repertoire"] },
    { title: "Love Is an Open Door", artist: "Frozen", tags: ["Repertoire"] },
    { title: "I Don't Want to Miss a Thing", artist: "Aerosmith", tags: ["Repertoire"] },
    { title: "Never Had a Dream Come True", artist: "S Club 7", tags: ["Repertoire"] },
    { title: "Hate (I Really Don't Like You)", artist: "Plain White T's", tags: ["Repertoire"] },
    { title: "I Just Can't Wait to Be King", artist: "The Lion King", tags: ["Repertoire"] },
    { title: "Hands Down", artist: "Dashboard Confessional", tags: ["Repertoire"] },
    { title: "Crawling", artist: "Hoobastank", tags: ["Repertoire"] },
    { title: "Back at One", artist: "Brian McKnight", tags: ["Repertoire"] },
    { title: "Before He Cheats", artist: "Carrie Underwood", tags: ["Repertoire"] },
    { title: "The Other Side", artist: "Jason Derulo", tags: ["Repertoire"] },
    { title: "Un-Break My Heart", artist: "Toni Braxton", tags: ["Repertoire"] },
    { title: "I Want It That Way", artist: "Backstreet Boys", tags: ["Repertoire"] },
    { title: "Baby Got Back", artist: "Sir Mix-A-Lot", tags: ["Repertoire"] },
    { title: "Nobody Speak", artist: "DJ Shadow ft. Run The Jewels", tags: ["Repertoire"] },
    { title: "Killing Me Softly", artist: "Fugees", tags: ["Repertoire"] },
    { title: "Dirty Little Secret", artist: "The All-American Rejects", tags: ["Repertoire"] },
    { title: "What's My Age Again?", artist: "Blink-182", tags: ["Repertoire"] },
    { title: "Let Me Love You", artist: "Mario", tags: ["Repertoire"] },
    { title: "Let Me Blow Ya Mind", artist: "Eve ft. Gwen Stefani", tags: ["Repertoire"] },
    { title: "Misery Business", artist: "Paramore", tags: ["Repertoire"] },
    { title: "I Want You Back", artist: "The Jackson 5", tags: ["Repertoire"] },
    { title: "A Thousand Miles", artist: "Vanessa Carlton", tags: ["Repertoire"] },
    { title: "Sk8er Boi", artist: "Avril Lavigne", tags: ["Repertoire"] },
    { title: "Nothing Better", artist: "The Postal Service", tags: ["Repertoire"] },
    { title: "Unwritten", artist: "Natasha Bedingfield", tags: ["Repertoire"] },
    { title: "Sugar, We're Goin Down", artist: "Fall Out Boy", tags: ["Repertoire"] },
    { title: "Papercut", artist: "Linkin Park", tags: ["Repertoire"] },
    { title: "U Don't Have to Call", artist: "Usher", tags: ["Repertoire"] },
    { title: "Kiss from a Rose", artist: "Seal", tags: ["Repertoire"] },
    { title: "There You'll Be", artist: "Faith Hill", tags: ["Repertoire"] },
    { title: "Come What May", artist: "Moulin Rouge", tags: ["Repertoire"] },
    { title: "Swing, Swing", artist: "The All-American Rejects", tags: ["Repertoire"] },
    { title: "Kiss Me", artist: "Sixpence None the Richer", tags: ["Repertoire"] },
    { title: "Bring Me to Life", artist: "Evanescence", tags: ["Repertoire"] },
    { title: "Semi-Charmed Life", artist: "Third Eye Blind", tags: ["Repertoire"] },
    { title: "Shape of You", artist: "Ed Sheeran", tags: ["Repertoire"] },
    { title: "Some Nights", artist: "Fun.", tags: ["Repertoire"] },
    { title: "2 Become 1", artist: "Spice Girls", tags: ["Repertoire"] },
    { title: "The Boy Is Mine", artist: "Brandy & Monica", tags: ["Repertoire"] },
    { title: "Can't Fight the Moonlight", artist: "LeAnn Rimes", tags: ["Repertoire"] },
    { title: "One Sweet Day", artist: "Mariah Carey & Boyz II Men", tags: ["Repertoire"] },
    { title: "There's Nothing Holdin' Me Back", artist: "Shawn Mendes", tags: ["Repertoire"] },
    { title: "Stitches", artist: "Shawn Mendes", tags: ["Repertoire"] },
    { title: "It Wasn't Me", artist: "Shaggy", tags: ["Repertoire"] },
    { title: "Black Hole Sun", artist: "Soundgarden", tags: ["Repertoire"] },
    { title: "Stay", artist: "Rihanna ft. Mikky Ekko", tags: ["Repertoire"] },
    { title: "Lovefool", artist: "The Cardigans", tags: ["Repertoire"] },
    { title: "Love Song", artist: "Sara Bareilles", tags: ["Repertoire"] },
    { title: "Build Me Up Buttercup", artist: "The Foundations", tags: ["Repertoire"] },
    { title: "Dive", artist: "Ed Sheeran", tags: ["Repertoire"] },
    { title: "No Scrubs", artist: "TLC", tags: ["Repertoire"] },
    { title: "The Power of Love", artist: "Celine Dion", tags: ["Repertoire"] },
    { title: "I'm Yours", artist: "Jason Mraz", tags: ["Repertoire"] },
    { title: "Superman", artist: "Eminem", tags: ["Repertoire"] },
    { title: "My Happy Ending", artist: "Avril Lavigne", tags: ["Repertoire"] },
    { title: "Ain't No Rest for the Wicked", artist: "Cage the Elephant", tags: ["Repertoire"] },
    { title: "When You Were Young", artist: "The Killers", tags: ["Repertoire"] },
    { title: "My Own Worst Enemy", artist: "Lit", tags: ["Repertoire"] },
    { title: "Alexander Hamilton", artist: "Hamilton", tags: ["Repertoire"] },
    { title: "All or Nothing", artist: "O-Town", tags: ["Repertoire"] },
    { title: "If I Ain't Got You", artist: "Alicia Keys", tags: ["Repertoire"] },
    { title: "Bye Bye Bye", artist: "NSYNC", tags: ["Repertoire"] },
    { title: "Ignition (Remix)", artist: "R. Kelly", tags: ["Repertoire"] },
    { title: "Every Time I Close My Eyes", artist: "Babyface", tags: ["Repertoire"] },
    { title: "Ocean Avenue", artist: "Yellowcard", tags: ["Repertoire"] },
    { title: "Motivation", artist: "Kelly Rowland", tags: ["Repertoire"] },
    { title: "Still Fly", artist: "Big Tymers", tags: ["Repertoire"] },
    { title: "Stuck", artist: "Stacie Orrico", tags: ["Repertoire"] },
    { title: "Everywhere", artist: "Michelle Branch", tags: ["Repertoire"] },
    { title: "Goodbye to You", artist: "Michelle Branch", tags: ["Repertoire"] },
    { title: "Runaway", artist: "Linkin Park", tags: ["Repertoire"] },
    { title: "Runaway Baby", artist: "Bruno Mars", tags: ["Repertoire"] },
    { title: "Helena", artist: "My Chemical Romance", tags: ["Repertoire"] },
    { title: "Truly Madly Deeply", artist: "Savage Garden", tags: ["Repertoire"] },
    { title: "Call Out My Name", artist: "The Weeknd", tags: ["Repertoire"] },
    { title: "Iris", artist: "Goo Goo Dolls", tags: ["Repertoire"] },
    { title: "Back Here", artist: "BBMak", tags: ["Repertoire"] },
    { title: "Old Town Road", artist: "Lil Nas X", tags: ["Repertoire"] },
    { title: "Mia", artist: "Bad Bunny ft. Drake", tags: ["Repertoire"] },
    { title: "Case of the Ex", artist: "Mya", tags: ["Repertoire"] },
    { title: "Higher", artist: "Rihanna", tags: ["Repertoire"] },
    { title: "Love on the Brain", artist: "Rihanna", tags: ["Repertoire"] },
    { title: "Alone", artist: "Heart", tags: ["Repertoire"] },
    { title: "Shallow", artist: "Lady Gaga & Bradley Cooper", tags: ["Repertoire"] },
    { title: "Hit 'Em Up Style (Oops!)", artist: "Blu Cantrell", tags: ["Repertoire"] },
    { title: "My Kind of Love", artist: "Emeli Sandé", tags: ["Repertoire"] },
    { title: "4 AM", artist: "Melanie Fiona", tags: ["Repertoire"] },
    { title: "Daddy Lessons", artist: "Beyoncé", tags: ["Repertoire"] },
    { title: "Angel of Mine", artist: "Monica", tags: ["Repertoire"] },
    { title: "Time After Time", artist: "Cyndi Lauper", tags: ["Repertoire"] },
    { title: "How Do I Live", artist: "LeAnn Rimes", tags: ["Repertoire"] },
    { title: "All Star", artist: "Smash Mouth", tags: ["Repertoire"] },
    { title: "Sunday Morning", artist: "Maroon 5", tags: ["Repertoire"] },
    { title: "Nice & Slow", artist: "Usher", tags: ["Repertoire"] },
    { title: "Everybody (Backstreet's Back)", artist: "Backstreet Boys", tags: ["Repertoire"] },
    { title: "I'm with You", artist: "Avril Lavigne", tags: ["Repertoire"] },
    { title: "The Middle", artist: "Jimmy Eat World", tags: ["Repertoire"] },
    { title: "Gone", artist: "NSYNC", tags: ["Repertoire"] },
    { title: "It's Gonna Be Me", artist: "NSYNC", tags: ["Repertoire"] },
    { title: "I'll Be Missing You", artist: "Puff Daddy", tags: ["Repertoire"] },
    { title: "You Oughta Know", artist: "Alanis Morissette", tags: ["Repertoire"] },
    { title: "Ironic", artist: "Alanis Morissette", tags: ["Repertoire"] },
    { title: "Genie in a Bottle", artist: "Christina Aguilera", tags: ["Repertoire"] },
    { title: "Never Too Far", artist: "Mariah Carey", tags: ["Repertoire"] },
    { title: "Reflection", artist: "Mulan", tags: ["Repertoire"] },
    { title: "I Just Had Sex", artist: "The Lonely Island", tags: ["Repertoire"] },
    { title: "Adagio", artist: "Lara Fabian", tags: ["Repertoire"] },
    { title: "I Believe in a Thing Called Love", artist: "The Darkness", tags: ["Repertoire"] },
    { title: "Last Resort", artist: "Papa Roach", tags: ["Repertoire"] },
    { title: "Firework", artist: "Katy Perry", tags: ["Repertoire"] },
    { title: "When I Was Your Man", artist: "Bruno Mars", tags: ["Repertoire"] },
    { title: "Open Arms", artist: "Journey", tags: ["Repertoire"] },
    { title: "Sway", artist: "The Pussycat Dolls", tags: ["Repertoire"] },
    { title: "Hurt", artist: "Christina Aguilera", tags: ["Repertoire"] },
    { title: "My All", artist: "Mariah Carey", tags: ["Repertoire"] },
    { title: "If That Mood", artist: "Esthero", tags: ["Repertoire"] },
    { title: "Chop Suey!", artist: "System of a Down", tags: ["Repertoire"] },
    { title: "Don't Speak", artist: "No Doubt", tags: ["Repertoire"] },
    { title: "Stop", artist: "Spice Girls", tags: ["Repertoire"] },
    { title: "Halo", artist: "Beyoncé", tags: ["Repertoire"] },
    { title: "I'm Not The Only One", artist: "Sam Smith", tags: ["Repertoire"] },
    { title: "You Know I'm No Good", artist: "Amy Winehouse", tags: ["Repertoire"] },
    { title: "Stronger Than Me", artist: "Amy Winehouse", tags: ["Repertoire"] },
    { title: "Gravity", artist: "Sara Bareilles", tags: ["Repertoire"] },
    { title: "Somebody That I Used to Know", artist: "Gotye", tags: ["Repertoire"] },
    { title: "Everlong", artist: "Foo Fighters", tags: ["Repertoire"] },
    { title: "Drive", artist: "Incubus", tags: ["Repertoire"] },
    { title: "Over My Head (Cable Car)", artist: "The Fray", tags: ["Repertoire"] },
    { title: "Put Your Records On", artist: "Corinne Bailey Rae", tags: ["Repertoire"] },
    { title: "At Last", artist: "Etta James", tags: ["Repertoire"] },
    { title: "Fairytale", artist: "Sara Bareilles", tags: ["Repertoire"] },
    { title: "On Bended Knee", artist: "Boyz II Men", tags: ["Repertoire"] },
    { title: "Welcome to My Life", artist: "Simple Plan", tags: ["Repertoire"] },
    { title: "I'll Be", artist: "Edwin McCain", tags: ["Repertoire"] },
    { title: "A Change Is Gonna Come", artist: "Sam Cooke", tags: ["Repertoire"] },
    { title: "Man! I Feel Like a Woman!", artist: "Shania Twain", tags: ["Repertoire"] },
    { title: "Leave the Door Open", artist: "Silk Sonic", tags: ["Repertoire"] },
    { title: "Lucky", artist: "Britney Spears", tags: ["Repertoire"] },
    { title: "U Got It Bad", artist: "Usher", tags: ["Repertoire"] },
    { title: "Cry Me a River", artist: "Justin Timberlake", tags: ["Repertoire"] },
    { title: "September", artist: "Earth, Wind & Fire", tags: ["Repertoire"] },
    { title: "Wrecking Ball", artist: "Miley Cyrus", tags: ["Repertoire"] },
    { title: "All by Myself", artist: "Celine Dion", tags: ["Repertoire"] },
    { title: "Santeria", artist: "Sublime", tags: ["Repertoire"] },
    { title: "Rumour Has It", artist: "Adele", tags: ["Repertoire"] },
    { title: "Set Fire to the Rain", artist: "Adele", tags: ["Repertoire"] },
    { title: "Let's Get It On", artist: "Marvin Gaye", tags: ["Repertoire"] },
    { title: "Drift Away", artist: "Uncle Kracker", tags: ["Repertoire"] },
    { title: "Calling All My Lovelies", artist: "Bruno Mars", tags: ["Repertoire"] },
    { title: "Love Hurts", artist: "Incubus", tags: ["Repertoire"] },
    { title: "The Bad Touch", artist: "Bloodhound Gang", tags: ["Repertoire"] },
    { title: "Heartbreak Anniversary", artist: "Giveon", tags: ["Repertoire"] },
    { title: "Take on Me", artist: "a-ha", tags: ["Repertoire"] },
    { title: "Still into You", artist: "Paramore", tags: ["Repertoire"] },
    { title: "Too Close", artist: "Next", tags: ["Repertoire"] },
    { title: "679", artist: "Fetty Wap", tags: ["Repertoire"] },
    { title: "Too Little Too Late", artist: "JoJo", tags: ["Repertoire"] },
    { title: "Only Hope", artist: "Mandy Moore", tags: ["Repertoire"] },
    { title: "Pleasantly Blue", artist: "4 Non Blondes", tags: ["Repertoire"] },
    { title: "What's Up?", artist: "4 Non Blondes", tags: ["Repertoire"] },
    { title: "Chasing Cars", artist: "Snow Patrol", tags: ["Repertoire"] },
    { title: "Addicted", artist: "Simple Plan", tags: ["Repertoire"] },
    { title: "Thnks fr th Mmrs", artist: "Fall Out Boy", tags: ["Repertoire"] },
    { title: "Kryptonite", artist: "3 Doors Down", tags: ["Repertoire"] },
    { title: "Creep", artist: "Radiohead", tags: ["Repertoire"] },
    { title: "My Neck, My Back", artist: "Khia", tags: ["Repertoire"] },
    { title: "Juice", artist: "Lizzo", tags: ["Repertoire"] },
    { title: "WAP", artist: "Cardi B ft. Megan Thee Stallion", tags: ["Repertoire"] },
    { title: "Leave (Get Out)", artist: "JoJo", tags: ["Repertoire"] },
    { title: "Rolling in the Deep", artist: "Adele", tags: ["Repertoire"] },
    { title: "Best Friend", artist: "Saweetie ft. Doja Cat", tags: ["Repertoire"] },
    { title: "Boulevard of Broken Dreams", artist: "Green Day", tags: ["Repertoire"] },
    { title: "Love", artist: "Keyshia Cole", tags: ["Repertoire"] },
    { title: "No One", artist: "Alicia Keys", tags: ["Repertoire"] },
    { title: "Absolutely (Story of a Girl)", artist: "Nine Days", tags: ["Repertoire"] },
    { title: "Under the Bridge", artist: "Red Hot Chili Peppers", tags: ["Repertoire"] },
    { title: "Meet in the Middle", artist: "Diamond Rio", tags: ["Repertoire"] },
    { title: "Complicated", artist: "Avril Lavigne", tags: ["Repertoire"] },
    { title: "Let Me Love You (Until You Learn to Love Yourself)", artist: "Ne-Yo", tags: ["Repertoire"] },
    { title: "Counting Stars", artist: "OneRepublic", tags: ["Repertoire"] },
    { title: "I Wanna Dance with Somebody", artist: "Whitney Houston", tags: ["Repertoire"] },
    { title: "Dancing in the Moonlight", artist: "Toploader", tags: ["Repertoire"] },
    { title: "Just Once", artist: "Quincy Jones ft. James Ingram", tags: ["Repertoire"] },
    { title: "Stand Out", artist: "A Goofy Movie", tags: ["Repertoire"] },
    { title: "Without You", artist: "Mariah Carey", tags: ["Repertoire"] },
    { title: "Pokémon Theme", artist: "Jason Paige", tags: ["Repertoire"] },
    { title: "If I Were a Boy", artist: "Beyoncé", tags: ["Repertoire"] },
    { title: "Breathe", artist: "Faith Hill", tags: ["Repertoire"] },
    { title: "Mamma Mia", artist: "ABBA", tags: ["Repertoire"] },
    { title: "Up", artist: "Cardi B", tags: ["Repertoire"] },
    { title: "Dog Days Are Over", artist: "Florence + The Machine", tags: ["Repertoire"] },
    { title: "What Makes You Beautiful", artist: "One Direction", tags: ["Repertoire"] },
    { title: "Smells Like Teen Spirit", artist: "Nirvana", tags: ["Repertoire"] },
    { title: "HUMBLE.", artist: "Kendrick Lamar", tags: ["Repertoire"] },
    { title: "This I Promise You", artist: "NSYNC", tags: ["Repertoire"] },
    { title: "The Ghost of You", artist: "My Chemical Romance", tags: ["Repertoire"] },
    { title: "Impossible", artist: "Christina Aguilera", tags: ["Repertoire"] },
    { title: "Part of Your World", artist: "The Little Mermaid", tags: ["Repertoire"] },
    { title: "What You Know", artist: "Two Door Cinema Club", tags: ["Repertoire"] },
    { title: "Slide", artist: "Goo Goo Dolls", tags: ["Repertoire"] },
    { title: "Hot in Herre", artist: "Nelly", tags: ["Repertoire"] },
    { title: "Kiss the Girl", artist: "The Little Mermaid", tags: ["Repertoire"] },
    { title: "Just a Girl", artist: "No Doubt", tags: ["Repertoire"] },
    { title: "Too Much", artist: "Spice Girls", tags: ["Repertoire"] },
    { title: "Vampire", artist: "Olivia Rodrigo", tags: ["Repertoire"] },
    { title: "You're Gonna Go Far, Kid", artist: "The Offspring", tags: ["Repertoire"] },
    { title: "Pretty Please", artist: "Dua Lipa", tags: ["Repertoire"] },
    { title: "Billie Jean", artist: "Michael Jackson", tags: ["Repertoire"] },
    { title: "Bad Romance", artist: "Lady Gaga", tags: ["Repertoire"] },
    { title: "When a Man Loves a Woman", artist: "Percy Sledge", tags: ["Repertoire"] },
    { title: "Pieces of Me", artist: "Ashlee Simpson", tags: ["Repertoire"] },
    { title: "Bathwater", artist: "No Doubt", tags: ["Repertoire"] },
    { title: "Soak Up the Sun", artist: "Sheryl Crow", tags: ["Repertoire"] },
    { title: "Can't Take My Eyes Off You", artist: "Frankie Valli", tags: ["Repertoire"] },
    { title: "Every Breath You Take", artist: "The Police", tags: ["Repertoire"] },
    { title: "Need You Now", artist: "Lady A", tags: ["Repertoire"] },
    { title: "My Humps", artist: "The Black Eyed Peas", tags: ["Repertoire"] },
    { title: "Party Up (Up in Here)", artist: "DMX", tags: ["Repertoire"] },
    { title: "Prince Ali", artist: "Aladdin", tags: ["Repertoire"] },
    { title: "Somewhere Only We Know", artist: "Keane", tags: ["Repertoire"] },
    { title: "Wonderwall", artist: "Oasis", tags: ["Repertoire"] },
    { title: "Royals", artist: "Lorde", tags: ["Repertoire"] },
    { title: "Seven Nation Army", artist: "The White Stripes", tags: ["Repertoire"] },
    { title: "I'll Be There for You", artist: "The Rembrandts", tags: ["Repertoire"] },
    { title: "I'll Make Love to You", artist: "Boyz II Men", tags: ["Repertoire"] },
    { title: "Love on the Rocks", artist: "Neil Diamond", tags: ["Repertoire"] },
    { title: "Separate Ways (Worlds Apart)", artist: "Journey", tags: ["Repertoire"] },
    { title: "Fergalicious", artist: "Fergie", tags: ["Repertoire"] },
    { title: "For Once in My Life", artist: "Stevie Wonder", tags: ["Repertoire"] },
    { title: "Be Prepared", artist: "The Lion King", tags: ["Repertoire"] },
    { title: "Lean Back", artist: "Terror Squad", tags: ["Repertoire"] },
    { title: "Higher", artist: "Creed", tags: ["Repertoire"] },
    { title: "That's Life", artist: "Frank Sinatra", tags: ["Repertoire"] },
    { title: "Sober", artist: "Childish Gambino", tags: ["Repertoire"] },
    { title: "How I Disappear", artist: "My Chemical Romance", tags: ["Repertoire"] },
    { title: "Say It Ain't So", artist: "Weezer", tags: ["Repertoire"] },
    { title: "Way Away", artist: "Yellowcard", tags: ["Repertoire"] },
    { title: "Last Name", artist: "Carrie Underwood", tags: ["Repertoire"] },
    { title: "Undo It", artist: "Carrie Underwood", tags: ["Repertoire"] },
    { title: "Cowboy Casanova", artist: "Carrie Underwood", tags: ["Repertoire"] },
    { title: "Self Esteem", artist: "The Offspring", tags: ["Repertoire"] },
    { title: "Electric Love", artist: "Børns", tags: ["Repertoire"] },
    { title: "I Knew I Loved You", artist: "Savage Garden", tags: ["Repertoire"] },
    { title: "A Moment Like This", artist: "Kelly Clarkson", tags: ["Repertoire"] },
    { title: "Dancing With A Stranger", artist: "Sam Smith & Normani", tags: ["Repertoire"] },
    { title: "Die With A Smile", artist: "Bruno Mars", tags: ["Repertoire"] },
    { title: "Take It Slow", artist: "John Legend", tags: ["Repertoire"] },
    { title: "The Anthem", artist: "Good Charlotte", tags: ["Repertoire"] },
    { title: "...Baby One More Time", artist: "Britney Spears", tags: ["Repertoire"] },
    { title: "Titanium", artist: "David Guetta ft. Sia", tags: ["Repertoire"] },
    { title: "Reptilia", artist: "The Strokes", tags: ["Repertoire"] },
    { title: "Like a G6", artist: "Far East Movement", tags: ["Repertoire"] },
    { title: "Airplanes", artist: "B.o.B ft. Hayley Williams", tags: ["Repertoire"] },
    { title: "The Door", artist: "Teddy Swims", tags: ["Repertoire"] },
    { title: "Lose Control", artist: "Teddy Swims", tags: ["Repertoire"] },
    { title: "Slow It Down", artist: "Benson Boone", tags: ["Repertoire"] },
    { title: "More Today Than Yesterday", artist: "Spiral Starecase", tags: ["Repertoire"] },
    { title: "Rollin'", artist: "Limp Bizkit", tags: ["Repertoire"] },
    { title: "Pursuit of Happiness", artist: "Kid Cudi", tags: ["Repertoire"] },
    { title: "Grind", artist: "Nikki", tags: ["Repertoire"] },
    { title: "Golden Hour", artist: "JVKE", tags: ["Repertoire"] },
    { title: "Heart Attack", artist: "Demi Lovato", tags: ["Repertoire"] },
    { title: "Enemy", artist: "Imagine Dragons", tags: ["Repertoire"] },
    { title: "Oscar Winning Tears.", artist: "RAYE", tags: ["Repertoire"] },
    { title: "Drops of Jupiter", artist: "Train", tags: ["Repertoire"] },
    { title: "I Love You Always Forever", artist: "Donna Lewis", tags: ["Repertoire"] },
    { title: "Torn", artist: "Natalie Imbruglia", tags: ["Repertoire"] },
    { title: "Show Me the Meaning of Being Lonely", artist: "Backstreet Boys", tags: ["Repertoire"] },
    { title: "Beautiful Things", artist: "Benson Boone", tags: ["Repertoire"] },
    { title: "9 to 5", artist: "Dolly Parton", tags: ["Repertoire"] },
    { title: "Want U Back", artist: "Cher Lloyd", tags: ["Repertoire"] },
    { title: "It's Tricky", artist: "Run-D.M.C.", tags: ["Repertoire"] },
    { title: "Take Me Out", artist: "Franz Ferdinand", tags: ["Repertoire"] },
    { title: "Dammit", artist: "Blink-182", tags: ["Repertoire"] },
    { title: "How You Remind Me", artist: "Nickelback", tags: ["Repertoire"] },
    { title: "DJ Got Us Fallin' in Love", artist: "Usher", tags: ["Repertoire"] },
    { title: "Always Be My Baby", artist: "Mariah Carey", tags: ["Repertoire"] },
    { title: "I Will Follow You into the Dark", artist: "Death Cab for Cutie", tags: ["Repertoire"] },

    // TOP
    { title: "Leave the Door Open", artist: "Silk Sonic", tags: ["Top"] },
    { title: "Runaway Baby", artist: "Bruno Mars", tags: ["Top"] },
    { title: "Paris (Ooh La La)", artist: "Grace Potter", tags: ["Top"] },
    { title: "Ocean Avenue", artist: "Yellowcard", tags: ["Top"] },
    { title: "I Believe in a Thing Called Love", artist: "The Darkness", tags: ["Top"] },
    { title: "All My Life", artist: "Foo Fighters", tags: ["Top"] },
    { title: "I'm Not Okay (I Promise)", artist: "My Chemical Romance", tags: ["Top"] },
    { title: "Still into You", artist: "Paramore", tags: ["Top"] },
    { title: "I'll Make a Man Out of You", artist: "Mulan", tags: ["Top"] },
    { title: "Blister in the Sun", artist: "Violent Femmes", tags: ["Top"] },
    { title: "Unwritten", artist: "Natasha Bedingfield", tags: ["Top"] },
    { title: "Lose Control", artist: "Teddy Swims", tags: ["Top"] },
    { title: "777", artist: "Silk Sonic", tags: ["Top"] },
    { title: "Rumour Has It", artist: "Adele", tags: ["Top"] },
    { title: "Hurt", artist: "Christina Aguilera", tags: ["Top"] },
    { title: "Impossible", artist: "Christina Aguilera", tags: ["Top"] },
    { title: "Differences", artist: "Ginuwine", tags: ["Top"] },
    { title: "It Will Rain", artist: "Bruno Mars", tags: ["Top"] },

    // TO TRY
    { title: "Ego Talking", artist: "Saint Harison", tags: ["To Try"] },
    { title: "Next to Me", artist: "Emeli Sandé", tags: ["To Try"] },
    { title: "I Need You", artist: "Alicia Keys", tags: ["To Try"] },
    { title: "I Hate Everything About You", artist: "Three Days Grace", tags: ["To Try"] },
    { title: "Counting Stars", artist: "OneRepublic", tags: ["To Try"] },
    { title: "The Climb", artist: "Miley Cyrus", tags: ["To Try"] },
    { title: "Goodbye Earl", artist: "The Chicks", tags: ["To Try"] },
    { title: "Locked Out of Heaven", artist: "Bruno Mars", tags: ["To Try"] },
    { title: "Sabotage", artist: "Beastie Boys", tags: ["To Try"] },
    { title: "Beggin'", artist: "Måneskin", tags: ["To Try"] },
    { title: "Addicted to You", artist: "Avicii", tags: ["To Try"] },
    { title: "Nasty Naughty Boy", artist: "Christina Aguilera", tags: ["To Try"] },
    { title: "Roses", artist: "OutKast", tags: ["To Try"] },
    { title: "Cold Hard Bitch", artist: "Jet", tags: ["To Try"] },
    { title: "Paralyzer", artist: "Finger Eleven", tags: ["To Try"] },
    { title: "Crazy for This Girl", artist: "Evan and Jaron", tags: ["To Try"] },
    { title: "Call Me When You're Sober", artist: "Evanescence", tags: ["To Try"] },
    { title: "We Belong Together", artist: "Mariah Carey", tags: ["To Try"] },

    // TO LEARN
    { title: "What's Your Fantasy", artist: "Ludacris", tags: ["To Learn"] },
    { title: "Mercy on Me", artist: "Christina Aguilera", tags: ["To Learn"] },
    { title: "Higher", artist: "Creed", tags: ["To Learn"] },
    { title: "Sabotage", artist: "Beastie Boys", tags: ["To Learn"] }
];
